name: Build Mobile App (Skyu Generated)
'on':
  push:
    branches:
      - main
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_7d763fce-6d44-4b64-be2c-415e8d389afa
env:
  ENCODED_PIPELINE_SECRET: >-
    ${{secrets.AWESOMEPROJECT01_ENV_85905F39A02F4772A5ACD424B2EF2862_APP_FFBB2C7D87DC4B739D847CC34D5CFF71_CHECK}}
  MOBILE_APP_BUILD_ENV_VERSION: '17'
  MOBILE_APP_DEPENDENCY_ENV_VERSION: '18'
  MOBILE_APP_ARTIFACT_PATH: android/app/build/outputs/apk/release/app-release.apk
  MOBILE_APP_DEPENDENCY_INSTALLATION: npm i -g yarn && npm i -g corepack && yarn install
  ANDROID_APP_FOLDER_PATH: android
jobs:
  build:
    name: Build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: >-
          echo " Starting GitHub Action!" && echo "IMAGE_EXISTS_IN_ECR=false" >>
          $GITHUB_ENV
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: 'Run :: Checkout Specific Commit'
        if: ${{ github.event.client_payload.commitId != null }}
        run: git checkout ${{ github.event.client_payload.commitId }}
      - name: 'Run :: Decoding Secrets 0de98f57-9d7e-4c08-90c7-5239cedca310'
        run: >-
          echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r
          'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo
          "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.MOBILE_APP_BUILD_ENV_VERSION }}
          distribution: adopt
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.MOBILE_APP_DEPENDENCY_ENV_VERSION }}
          cache: npm
      - name: Install Dependencies
        run: ${{ env.MOBILE_APP_DEPENDENCY_INSTALLATION }}
      - name: Build application
        run: cd ${{ env.ANDROID_APP_FOLDER_PATH }} && ./gradlew assembleRelease
      - name: Build and Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ${{ env.MOBILE_APP_ARTIFACT_PATH }}
          retention-days: '3'
