name: Build Mobile App (Skyu Generated)
'on':
  push:
    branches:
      - main
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_2e25e1ba-cf51-418d-b1d9-93e485d0d86c
env:
  ENCODED_PIPELINE_SECRET: >-
    ${{secrets.AWESOMEPROJECT01_ENV_85905F39A02F4772A5ACD424B2EF2862_APP_FFBB2C7D87DC4B739D847CC34D5CFF71_CHECK}}
  MOBILE_APP_BUILD_ENV_VERSION: '17'
  BUILD_ENVIRONEMENT_VERSION: '18'
  MOBILE_APP_ARTIFACT_PATH: android/app/build/outputs/apk/release/app-release.apk
  MOBILE_APP_DEPENDENCY_INSTALLATION: npm i -g corepack && npm i
  ANDROID_APP_FOLDER_PATH: android
jobs:
  build:
    name: Build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: >-
          echo " Starting GitHub Action!" && echo "IMAGE_EXISTS_IN_ECR=false" >>
          $GITHUB_ENV
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: 'Run :: Checkout Specific Commit'
        if: ${{ github.event.client_payload.commitId != null }}
        run: git checkout ${{ github.event.client_payload.commitId }}
      - name: 'Run :: Decoding Secrets 3a81af03-2109-4c92-9603-5c5d3b7d625d'
        run: >-
          echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r
          'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo
          "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
      - name: 'Run :: Install Java'
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.MOBILE_APP_BUILD_ENV_VERSION }}
          distribution: adopt
          cache: gradle
      - name: 'Run :: Validate Gradle wrapper'
        uses: gradle/wrapper-validation-action@v1
      - name: 'Run :: Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.BUILD_ENVIRONEMENT_VERSION }}
      - name: 'Run :: Install Dependencies'
        run: ${{ env.MOBILE_APP_DEPENDENCY_INSTALLATION }}
      - name: 'Run :: Build application'
        run: cd ${{ env.ANDROID_APP_FOLDER_PATH }} && ./gradlew assembleRelease
      - name: 'Run :: Build and Upload application'
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ${{ env.MOBILE_APP_ARTIFACT_PATH }}
          retention-days: '3'
