name: Build Mobile App (Skyu Generated)
'on':
  push:
    branches:
      - main
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_6bcb5527-5c44-4772-afbe-99b27153f370
env:
  ENCODED_PIPELINE_SECRET: >-
    ${{secrets.AWESOMEPROJECT01_ENV_85905F39A02F4772A5ACD424B2EF2862_APP_FFBB2C7D87DC4B739D847CC34D5CFF71_CHECK}}
  MOBILE_APP_DEPENDENCY_ENV: NODE
  MOBILE_APP_BUILD_ENV: JAVA
  MOBILE_APP_BUILD_ENV_VERSION: '17'
  MOBILE_APP_DEPENDENCY_ENV_VERSION: '18'
  MOBILE_APP_ARTIFACT_PATH: android/app/build/outputs/apk/release/app-release.apk
jobs:
  build:
    name: Build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: >-
          echo " Starting GitHub Action!" && echo "IMAGE_EXISTS_IN_ECR=false" >>
          $GITHUB_ENV
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: 'Run :: Checkout Specific Commit'
        if: ${{ github.event.client_payload.commitId != null }}
        run: git checkout ${{ github.event.client_payload.commitId }}
      - name: 'Run :: Decoding Secrets bfe155db-81b5-4655-9a9b-75ac52fb7a5b'
        run: >-
          echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r
          'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo
          "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.MOBILE_APP_DEPENDENCY_ENV_VERSION }}
          cache: npm
      - name: Run Yarn Install
        run: npm i -g corepack && npm install
      - name: Build application
        run: cd ./android && ./gradlew assembleRelease
      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ${{ env.MOBILE_APP_ARTIFACT_PATH }}
          retention-days: '3'
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.MOBILE_APP_BUILD_ENV_VERSION }}
          distribution: adopt
          cache: gradle
